Better handle corrupted .gitsubmodule (#10691)
gitextensions/gitextensions pull request #10695
Opened 2023-02-02 09:28 UTC by bansan85

Fixes #10691

## Proposed changes

- Add try/catch around function that throw due to wrong .gitsubmodule file.

## Test environment(s)

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2023-02-02 21:14 UTC, mstv reviewed
How does it look now if .gitsubmodule is corrupted?
I am afraid there is no indication but the lack of displayed submodule status.

2023-02-02 22:36 UTC, RussKie commented
The changes look sensible. Could you please provide screenshots for the new
experience?

On Fri, 3 Feb 2023 at 08:14, Michael Seibt ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> How does it look now if .gitsubmodule is corrupted?
> I am afraid there is no indication but the lack of displayed submodule
> status.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/10695#pullrequestreview-1281905963>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBTEXVNZIGJAOER56E5TQDWVQPTVANCNFSM6AAAAAAUOYZ7PQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-02-10 10:33 UTC, bansan85 commented
Without try/catch in `GitModule.GetSubmodule`, the commit looks like:

![image](https://user-images.githubusercontent.com/9248729/218065456-75c51c16-4be9-408d-9f54-436a87b9f3cb.png)

After try/catch:

![image](https://user-images.githubusercontent.com/9248729/218065509-27ea6347-54c2-420b-8172-11d74bdf6e17.png)

![image](https://user-images.githubusercontent.com/9248729/218070150-d667d853-e19a-4063-bae6-9ca24ed0133c.png)


I do not have any trouble if I check the option `Refresh dialog on form focus`.

If the `GitModule.GetSubmodule` is fixed, I can't reproduce the second error (see error below). So, I removed the try/catch around `GetCurrentSubmoduleChangesAsync`.

![image](https://user-images.githubusercontent.com/9248729/216272896-bf8f55b5-65d5-46e3-a343-65676a967ee9.png)

2023-02-10 11:02 UTC, bansan85 commented
I still have this error message.

![image](https://user-images.githubusercontent.com/9248729/218076031-33965407-cdad-4423-9801-ff02cca18035.png)

But I don't know if I should fix it.

2023-02-10 21:35 UTC, mstv commented
The screenshots LGTM.

> I still have this error message.
> 
> ![image](https://user-images.githubusercontent.com/9248729/218076031-33965407-cdad-4423-9801-ff02cca18035.png)
> 
> But I don't know if I should fix it.

There is nothing to be fixed IMO. Git cannot process the submodules until the conflict in the configuration file will have been fixed. So it is correct to display an error.

2023-02-10 21:47 UTC, mstv requested changes

2023-02-10 21:47 UTC, mstv commented on GitCommands/Git/GitModule.cs
> +            }
This function `GetSubmodule` is used in many other functions.
Converting an exception into `GitModule(null)` might cause other less clear exceptions.

Rather handle the exception in `SubmoduleHelpers.ParseSubmodulePatchStatus` and return the error in an `GitSubmoduleStatus` instance. (If I have not identified the correct function used by FormCommit, please do something similar in the correct function.)

2023-02-10 21:50 UTC, mstv commented
The final screenshots should be added to the PR description. Grabbing them from comments after a lengthy discussion is error-prone.

2023-06-18 04:05 UTC, RussKie commented
@bansan85 is this something you are still planning to work on?

2023-07-09 13:00 UTC, closed without merging