Add option to set category to FormClone/FormInit
gitextensions/gitextensions pull request #11403
Opened 2023-11-27 21:52 UTC by dmitrybozhenok

Fixes #11312 

## Proposed changes
Add an option to assign a category on creating or cloning a repository via an editable combobox (disabled by default). I don't think it makes sense from UX point of view to add it also to FormOpen. 

## Screenshots 

### Before
![image](https://github.com/gitextensions/gitextensions/assets/23001472/b9e5c634-eaab-4f3c-974d-87044983ddae)
![image](https://github.com/gitextensions/gitextensions/assets/23001472/91de93d9-503c-42f1-bcfa-9c76fba2344e)

### After
![image](https://github.com/gitextensions/gitextensions/assets/23001472/d1aceba5-1d5c-4528-8212-5582c18f7099)
![image](https://github.com/gitextensions/gitextensions/assets/23001472/2f6ebb3e-dea5-4cfb-bf09-81aaa3d65061)
![image](https://github.com/gitextensions/gitextensions/assets/23001472/0f0a3628-a9cb-4175-9f1f-4f7c516d84b0)
![image](https://github.com/gitextensions/gitextensions/assets/23001472/e481ebd1-3b4b-4963-9a64-1b268764fe1d)

## Test methodology 

Manual testing.

## Test environment(s) 

- GIT 2.43.0
- Microsoft Windows NT 10.0.22621.0

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2023-11-27 22:18 UTC, pmiossec requested changes
A lot of duplicated code. Could you create a class that will handle most of the logic?

2023-11-27 22:38 UTC, pmiossec commented
Oh! And you need to run the `update-loc.cmd` script at the repo root and commit the translation file updated.

2023-11-27 22:58 UTC, dmitrybozhenok commented
Thank you for the suggestions, will do!

2023-11-28 00:13 UTC, RussKie commented
The current dialog layout is not great, please move the new control as follows:
![image](https://github.com/gitextensions/gitextensions/assets/4403806/16c8c1d3-ba63-4aea-aeae-2dad1b713db8)

There's no need for the checkbox - the empty selection implies no category assignment.

Please ensure the tab order of the dialogs remains logical.

2023-11-28 00:15 UTC, RussKie commented
> A lot of duplicated code. Could you create a class that will handle most of the logic?

Please create a new user control that encapsulates all the necessary logic.

2023-12-12 10:52 UTC, dmitrybozhenok commented
Apologies for delay, had other commitments, planning to finish this one soon.

2026-06-14 11:50 UTC, RussKie commented
Feel free to re-open, when you decide to get back to it.

2026-06-14 11:50 UTC, closed without merging