Restore splitter positions early in the layout process for FormCommit
gitextensions/gitextensions pull request #11646
Opened 2024-03-19 20:39 UTC by mdonatas

## Proposed changes

- Splitters in `FormCommit` are restored after layout is already done causing quite some visible re-drawing
- Since all controls are ready early in the layout cycle, restore splitters before performing initial form layout

## Screenshots 

### Before
Notice the unstaged/staged controls getting resized during the loading of the form (video is slowed down 3x)

https://github.com/gitextensions/gitextensions/assets/483659/245e63e7-7eb3-479e-8f81-0579fc87ae4b

### After

https://github.com/gitextensions/gitextensions/assets/483659/b069b8d5-da8c-4d4c-991d-a93b5c869745

## Test methodology 

- Manually for several days

## Test environment(s) 

- Windows 11
- DPI 200%

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2024-03-19 20:40 UTC, mdonatas commented
This, to me personally, is a big improvement to the GE experience since I open commit form quite often and almost always notice the flicker 😊

2024-03-19 21:32 UTC, mstv submitted a review, later dismissed
have not run

2024-03-19 23:19 UTC, mstv reviewed
👍 works well

2024-03-19 23:19 UTC, mstv approved these changes

2024-03-21 17:07 UTC, pmiossec requested changes
Works good but need to move the call outside `.Designer.cs` file.

2024-03-21 17:07 UTC, pmiossec commented on GitUI/CommandsDialogs/FormCommit.Designer.cs
> +            RestoreSplitters();
We can't put code in `.Designer.cs` file otherwise it will be removed if some changes are made with the designer and it will be difficult to notice the line removed.
From a quick testing, putting the call just after the call of `InitializeComponent()` is working fine also

2024-03-21 17:22 UTC, mdonatas commented on GitUI/CommandsDialogs/FormCommit.Designer.cs
> +            RestoreSplitters();
I can add a test to guard against that. In my very rough (frame counting) and imperfect (debug mode) testing it was performing ~50ms slower.. which makes sense since layout needs to be performed more times.

Also, there are already forms (which inherit other forms) and they set protected properties in `.Designer.cs` which get deleted each time a designer is saved. So it's not unprecedented.

`FormCommit` is already very slow, it takes ~1s to open! I would expect ~100ms so willingly worsening performance is something should be avoided.

2024-03-21 18:22 UTC, mdonatas commented on GitUI/CommandsDialogs/FormCommit.Designer.cs
> +            RestoreSplitters();
@pmiossec I've added a splitter restoration test to prevent accidental removal of `RestoreSplitters();`

2024-03-22 08:21 UTC, pmiossec commented on GitUI/CommandsDialogs/FormCommit.Designer.cs
> +            RestoreSplitters();
I'm not fond of but I understand the point of view.
So it deserve at least a comment to explain and so that it is clear that it is put there on purpose and become evident if the lines are deleted during a UI change.

I'm not an expert in WinForms so I will let other more experienced decide. A point of view @RussKie ?

2024-03-22 08:23 UTC, pmiossec reviewed
I won't block the merge anymore but I'm waiting for a comment added at least.

2024-03-22 08:23 UTC, pmiossec approved these changes

2024-03-23 13:18 UTC, RussKie commented on GitUI/CommandsDialogs/FormCommit.Designer.cs
> +            RestoreSplitters();
@mdonatas first of all thank you for the submission, I've been down this rabbit hole, and I truly appreciate your efforts.

However, @pmiossec is correct - the designer file, or `InitializeComponent` method to be precise, is the method "owned" by the Windows Forms designer which it rewrites at will whenever the form is loaded into the designer. And since we can't guarantee this form won't be opened in the designer we should be avoiding manual changes in this method.
I'm not really sure what's a good (or even "acceptable") solution here...

> FormCommit is already very slow, it takes ~1s to open! I would expect ~100ms so willingly worsening performance is something should be avoided.

It is true, and it is true for `FormBrowse` as well. I've spent some time looking at these problems before, and those were rooted pretty deep and required some fundamental changes. In the nutshell, both of these forms perform way too much work in the constructors and before the forms are shown to the user. In my view this is incorrect, the forms have to be shown blank and the data then should be dynamically/asynchronously loaded.

I'm not sure there are easy answers or solutions to any of those issues.

To that extent I even prototyped a POC where I had a "shell" which would load "views" into itself (https://github.com/RussKie/gitextensions/tree/add_shell_take2), and that had pretty nice perf. That POC prompted other work such as the introduction of IoC and `IServiceProvider` (https://github.com/gitextensions/gitextensions/pull/11142 and all the follow ups), the rework of the `IGitModule` use (https://github.com/gitextensions/gitextensions/pull/11269) and further consideration for how it all fits with the extensibility model (https://github.com/gitextensions/gitextensions/pull/11431)... In other words, it's a loooong road (the road to hell is full of good intensions 😄).

2024-03-23 13:25 UTC, RussKie reviewed
I can see where you're coming from, and whilst this is super unrecommended way of doing things - because `InitializeComponent` method is owned by the Windows Forms designer, and the code within will be rewritten at will by the designer, if we choose to go down this route we'll need additional safeguards that'll break immediately should we fail to detect when the `RestoreSplitters()` method is not called.

E.g., `RestoreSplitters()` should set some bit flag, and then the flag should be checked (e.g., in `OnLoaded()`), and if the flag is unset - fail. This could be a DEBUG-only guard.

2024-03-23 14:18 UTC, mdonatas commented
@RussKie regarding the safeguards, do you think something else is necessary in addition to the test? I've added a test which moves the splitter and checks that it is at a correct distance in subsequent open.

Also, part of the reason why I thought this approach is ~ _fine_ ~ is because I rather recently had experienced work in FormRebase which does this 👇 after saving of the designer window. It was annoying but most of development process is 😅
![image](https://github.com/gitextensions/gitextensions/assets/483659/12bfdabc-69c2-42a0-a4ba-267771abbea1)

2024-03-24 03:47 UTC, RussKie commented
> Also, part of the reason why I thought this approach is ~ _fine_ ~ is because I rather recently had experienced work in FormRebase which does this 👇 after saving of the designer window

It shouldn't be doing that... IDK, man... The designer stuff is hard and arcane.

2024-03-24 03:47 UTC, merged