Improve pinned repos handling
gitextensions/gitextensions pull request #11779
Opened 2024-06-04 13:12 UTC by pmiossec

- Add a icon to clearly see pinned repositories
- Add an option to remove pinned repositories from recent repositories (to not have duplicate repositories and save space --and user brain CPU cycles--)
- Remove "Maximum number of pinned recent repositories" because if user add a repository to the pinned list, it's to see it (otherwise he will remove it from the list)

## Screenshots 

### Before

no "pinned" icons & repos duplicated

![image](https://github.com/gitextensions/gitextensions/assets/460196/107c836e-aca6-4281-b3b6-29299fc385ac)

### After

Pinned repos with icon:

![image](https://github.com/gitextensions/gitextensions/assets/460196/d14b3d3a-65cb-4ed5-8f56-7e9fed570c14)

With pinned repos not deduplicated (as before):
![image](https://github.com/gitextensions/gitextensions/assets/460196/831a3f21-3216-46c3-8f04-070118c4e5c9)

With pinned repos deduplicated (so less repo lines displayed) :

![image](https://github.com/gitextensions/gitextensions/assets/460196/c8cf5278-d32c-491c-88bd-76327e8c4e11)

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 392712e717aa06c55419142557156ff185d597a3
- Git 2.45.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.5
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

## Merge strategy

I agree that the maintainer rebase merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2024-06-04 21:05 UTC, mstv requested changes
🤔 As I complained about when the regarding config form was modified, the term "pinned" may apply for the dashboard. But it does not correctly describe the behavior of the repo dropdown - at least not for the mode I use:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/23102060-9459-45b3-b874-c6e643a0ac2b)

(Yes, this is how it looks. And the single column is not resizable!)

In this dropdown, the first list is just the MRU entries (sorted by usage), the second list is - more or less - the list of all repos I use - in alphabetical order.

Deduplication really needs to optional. A regarding screenshot is missing in the PR description.

The "Maximum number of pinned recent repositories" needs to be kept as I do not pin repos and do not want to do it (as well as I do not know how to pin them except using the dashboard).

Failing tests need to be adapted.

2024-06-05 10:19 UTC, pmiossec commented
> (Yes, this is how it looks. And the single column is not resizable!)

This is due to the value 40 that you put in "Combobox minimum width" setting. I don't really know the goal of this setting and always untouched the default 0 value.

And investigating the code, that's the reason of your not readable display in #11768

2024-06-05 16:37 UTC, mstv commented
> This is due to the value 40 that you put in "Combobox minimum width" setting.

Yes, it must have been me 1-2 years ago. But I do not remember how and why - most likely while reviewing a PR.

2024-06-12 13:28 UTC, pmiossec commented
> 🤔 As I complained about when the regarding config form was modified, the term "pinned" may apply for the dashboard. But it does not correctly describe the behavior of the repo dropdown - at least not for the mode I use:
> 
> In this dropdown, the first list is just the MRU entries (sorted by usage), the second list is - more or less - the list of all repos I use - in alphabetical order.
> 
> Deduplication really needs to optional. A regarding screenshot of the setting is missing in the PR description.
> 
> The "Maximum number of pinned recent repositories" needs to be kept as I do not pin repos and do not want to do it (as well as I do not know how to pin them except using the dashboard).
> 
> Failing tests need to be adapted.

2nd version a lot simplified that handle all your remarks...

2024-06-12 21:21 UTC, mstv reviewed
"number of pinned repos" is the wrong term for this dropdown.
Have a look at the screenshot of deduplication in the PR description.

2024-06-12 21:21 UTC, mstv commented on src/app/GitCommands/Settings/AppSettings.cs
> +
Please do it like `ShowSearchCommit`.

2024-06-12 21:21 UTC, mstv commented on tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
> +                yield return (properties[nameof(AppSettings.HidePinnedFromRecentList)], false, false, false);
ditto

2024-06-13 17:38 UTC, mstv commented
My 2ct: Yes, "top repositories" and "pin to ..." feel much clearer to me.

2024-06-13 18:04 UTC, gerhardol commented
"top repositories" is better (major change to rename all variables/methods if that is done though)
top/recent makes sense.

I have a minor preference for anchor vs pin and am not voting for to have an icon for top repos at all

--
I usually have a short list with 5 top repos in MRU order and 50 in alphabetic order, including the top repos as I may not look there at all.
50 is too few to keep in the big list for me, I would like to have 500. But this requires the filtering RussKie started implementing, and to limit the size of the dropdown as larger than window is behaving very weird.

2024-06-26 18:14 UTC, mstv commented on src/app/GitCommands/UserRepositoryHistory/RecentRepoInfo.cs
> +                    where (!mostRecent && !HideTopRepositoriesFromRecentList) || repo.MostRecent == mostRecent
`mostRecent` and `MostRecent` should be renamed to `TopRepo`.
```suggestion
                    where repo.TopRepo == topRepo || (!topRepo && !HideTopRepositoriesFromRecentList) 
```

2024-06-26 18:14 UTC, mstv commented on tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
> +                yield return (properties[nameof(AppSettings.HideTopRepositoriesFromRecentList)], false, false, false);
```suggestion
                yield return (properties[nameof(AppSettings.HideTopRepositoriesFromRecentList)], false, isNotNullable, isISetting);
```

2024-07-11 09:45 UTC, pmiossec commented
@gerhardol Is my answer satisfying? or you still want me to remove the anchor icon from this PR ?

I can do it easily. I think the added value of this PR is more the "hide" setting.

2024-07-11 15:55 UTC, mstv approved these changes
LGTM

2024-07-13 22:09 UTC, gerhardol commented
> @gerhardol Is my answer satisfying? or you still want me to remove the anchor icon from this PR ?

I can live with the change.
I did not intend to block this change.
(but I want the list to be sorted by path rather than what the shortening happen to call them, but I missed that feedback on the previous PR...)

2024-07-15 13:46 UTC, pmiossec commented
> I can live with the change.

I can add an hidden setting, the added complexity will be very low...

> (but I want the list to be sorted by path rather than what the shortening happen to call them, but I missed that feedback on the previous PR...)

It seems completely counterintuitive to me: we will sort on something not displayed and the result won't appear sorted and the user won't really understand why. And I imagine that it will add some more code complexity...

I at least think that it should be discussed (in another issue) and so won't be part of this PR (so I rebased it, ready to be merged).

2024-07-18 21:13 UTC, merged