Address  CVE-2019-0820
gitextensions/gitextensions pull request #12031
Opened 2024-11-09 02:38 UTC by RussKie

See https://github.com/advisories/GHSA-cmhx-cq75-c4mj

![image](https://github.com/user-attachments/assets/17896d75-d5d9-44c1-8e8b-90444175db4a)

## Merge strategy

I agree that the maintainer squash merge this PR (if the commit message is clear).

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2024-11-09 21:12 UTC, gerhardol approved these changes

2024-11-09 21:12 UTC, gerhardol commented on Directory.Packages.props
> +
nit pick spaces

2024-11-09 21:20 UTC, gerhardol requested changes
build fails
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50955847#L245
Could not find reference "C:\Users\appveyor\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0.3\ref\System.Runtime.dll"

2024-11-09 22:00 UTC, mstv commented
local build with VS 17.5.11 works for me without issues

2024-11-12 07:25 UTC, mstv commented
`dotnet build` searches for
`"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0.3\ref\System.Runtime.dll"`
but the existing folder is named
`"C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\"`

2024-11-12 12:26 UTC, RussKie commented
Thank you, folks.

2024-11-12 20:44 UTC, mstv approved these changes

2024-11-12 22:33 UTC, gerhardol approved these changes

2024-11-12 22:59 UTC, merged