Colorblind syntax colors
gitextensions/gitextensions pull request #8426
Opened 2020-08-29 12:18 UTC by NikolayXHD

before
![image](https://user-images.githubusercontent.com/12046452/91636594-7e6f0900-ea0a-11ea-8655-8f4d59aadad8.png)

after
![image](https://user-images.githubusercontent.com/12046452/91636599-88910780-ea0a-11ea-9cbd-129b350d666a.png)

2020-08-29 19:38 UTC, gerhardol reviewed
The changes look fine to me.
The looks is not great, but this change is not for me anyway. (I always prefer usability before looks.)

@itsho @neil5280 
Is this something you see as an improvement?

2020-08-29 20:53 UTC, NikolayXHD commented
> The changes look fine to me.
> The looks is not great, but this change is not for me anyway. (I always prefer usability before looks.)

From what you say I guess I did not describe the PR change clearly. The colors are only altered if "Colorblind" checkbox is set.

2020-08-29 21:12 UTC, gerhardol commented
> From what you say I suspect I did not describe the PR change clearly. The colors are only altered if "Colorblind" checkbox is set.

The description is clear. The only I can say about the colors (normal color view for me) is that they do not look good - but this is not for me.
The reasoning about the change makes sense to me.

2020-08-30 04:19 UTC, neil5280 commented
> The changes look fine to me.
> The looks is not great, but this change is not for me anyway. (I always prefer usability before looks.)
> 
> @itsho @neil5280
> Is this something you see as an improvement?

For my color blindness, the shift in colors for the difference viewer were not advantageous, making the changed code look like unchanged code:

![image](https://user-images.githubusercontent.com/1786825/91651103-1980d680-ea3d-11ea-9284-9eaf885b184f.png)

The shifts in the color on the build status were helpful.

This highlights the difficulties in creating a one-size-fits-all automatic adjustment for those affected by color-blindness.

2020-09-05 13:49 UTC, NikolayXHD commented
> For my color blindness, the shift in colors for the difference viewer were not advantageous, making the changed code look like unchanged code:
> 
> ![image](https://user-images.githubusercontent.com/1786825/91651103-1980d680-ea3d-11ea-9284-9eaf885b184f.png)

Adjusted the formula to reduce color contrast loss,
![image](https://user-images.githubusercontent.com/12046452/92306337-fdc68480-ef96-11ea-902a-06337d04e963.png)

2020-09-05 13:56 UTC, hani77979 approved these changes

2020-09-05 13:58 UTC, hani77979 commented
G

2020-09-05 15:22 UTC, RussKie commented
I plan to review this in the next few days.

On Sat, 5 Sep. 2020, 11:58 pm hani77979, <notifications@github.com> wrote:

> G
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/8426#issuecomment-687615179>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBTEXTOG2Y424D5VER6X5TSEI7XVANCNFSM4QO632TQ>
> .
>

2020-09-05 18:14 UTC, NikolayXHD commented
> I plan to review this in the next few days.

@RussKie then I hold this PR and also #8424

2020-09-07 00:39 UTC, RussKie commented
@NikolayXHD thank you for doing this!
If this doesn't affect the default theming, and only affects users with visual impairments - I defer approval to them.

2020-09-21 16:47 UTC, NikolayXHD commented
> @NikolayXHD thank you for doing this!
> If this doesn't affect the default theming, and only affects users with visual impairments - I defer approval to them.

@neil5280, @itsho It's up to your approve now. See screenshots in PR title, they are up-to-date with current PR code.

2020-09-21 19:33 UTC, itsho commented
I've asked my colorblind friend and he says it looks great!
Thank you - to everyone involved in this!

2020-09-22 09:02 UTC, neil5280 commented
Contrast is improved.  Thanks for asking.

2020-09-27 11:18 UTC, RussKie requested changes
Blocking until #8424 is merged.

2020-09-29 00:09 UTC, merged