Add tests for AppSettings
gitextensions/gitextensions pull request #8469
Opened 2020-09-20 00:41 UTC by ivangrek

## Proposed changes

- Less magic values
- More tests

## Screenshots 

### Before

### After

## Test methodology 

- Manual
- Automation

## Test environment(s) 

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2020-09-21 08:41 UTC, RussKie commented
There is a lot of effort, but I can't sign off on these changes for a number of reasons.

We are adding a lot of code that has no user value, adds additional maintenance overhead, and is for test purposes only.
That is, to add a new setting we need to add a new const, and then reference it in the code.

We are also adding public const.  Const values get inlined during compilation times, which essentially binds us to these values forever - we won't be able to change those without risking breaking plugins, that may have taken dependencies on these values.
In the last 4 years alone we have tweaked/or talked about flipping defaults on selected settings. We won't be able to do this.

Perhaps what we could do instead is to update tests to assert the current default value without relying on typed "defaults", e.g. (pseudo code):
```cs
        private static IEnumerable<(string propertyName, object defaultTypeValue)> GetDefaultValue()
        {
            yield return (nameof(AppSettings.TelemetryEnabled), true);
            ....
        }
```

2020-09-21 10:28 UTC, RussKie commented
Also something on my radar (but hasn't reached the top priority) - look at how we implemented test accessors in Windows Forms repo: https://github.com/dotnet/winforms/pull/3225. It employs reflection as oppose to how we implemented them here (via TestAccessor structs).
This may be specifically useful in your scenarios.

2020-09-21 10:35 UTC, ivangrek commented
I tried to link defaults and settings. This is also part of the test.

2020-09-21 10:38 UTC, ivangrek commented
> Perhaps what we could do instead is to update tests to assert the current default value without relying on typed "defaults", e.g. (pseudo code):

We will double the number of magic values ​​in the code. )

2020-09-21 12:49 UTC, RussKie commented
> We will double the number of magic values ​​in the code. )

Yes, and no - values for the default values (a mouth full) are not valuable on their own. If values need changing we'll have a discussion and an associated change, that will include the change in AppSettings and a change in an associated test.

2020-09-21 14:27 UTC, ivangrek commented
Removed constants

2020-09-21 23:13 UTC, ivangrek commented
At least weirdness has already been identified.

> `yield return (nameof(AppSettings.TelemetryEnabled), true);`

And in fact.

`yield return (nameof(AppSettings.TelemetryEnabled), null);`

As I think it should be a non-nullable boolean.

2020-09-27 13:02 UTC, RussKie requested changes
👍 with few comments

2020-09-27 13:02 UTC, RussKie commented on UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
> +        }
💭  I don't typically like using local functions, but I think here is a good scenario to use them and move all the utility methods into `TestCases` so they don't pollute the class namespace.

2020-09-27 13:44 UTC, ivangrek commented on UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
> +                    }
Null value can apply only for nullable type whre defaultTypeValue is null.

2020-09-28 00:34 UTC, RussKie commented on UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
> +                    }
So we should invert to 
```cs
if (defaultTypeValue is null && value is null) { ... }
else { ... }
```
?

2020-09-28 05:52 UTC, RussKie approved these changes

2020-09-28 05:53 UTC, merged

2020-09-28 05:53 UTC, RussKie commented
🚀