Add a button to be able to open Application and User theme folders
gitextensions/gitextensions pull request #8502
Opened 2020-10-01 21:35 UTC by pmiossec

Fixes https://github.com/gitextensions/gitextensions/pull/8424#issuecomment-688712943

## Proposed changes

- Add a button to be able to open Application and User theme folders

## Screenshots 

### Before

(same than after without the button)

### After

![image](https://user-images.githubusercontent.com/460196/94865366-bf10d680-043d-11eb-9069-6d8eb19b9a6d.png)

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build 62fcfcbd924a264d34b02ae9831749acc43fef8f (Dirty)
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4240.0
- DPI 192dpi (200% scaling)

2020-10-02 00:45 UTC, RussKie commented
> ![image](https://user-images.githubusercontent.com/460196/94865366-bf10d680-043d-11eb-9069-6d8eb19b9a6d.png)
> 

I think it was discussed (or even proposed) to not have everything on one line in the "Themes" groupbox, as it makes a rather awkward UX.
Could you please move each element to its own row (this should be a table layout panel).

```
-- Themes ----

Current theme: [ darksilver v]
[x] Colorblind
[ ] Use system-defined...

[ Open user folder ] (<-- button)
```

I'm not sure if the "Open app folder" button is really needed though - it feels like it is complicating the UI for a little gain. 🤔

2020-10-02 19:51 UTC, gerhardol commented
> I'm not sure if the "Open app folder" button is really needed though - it feels like it is complicating the UI for a little gain.

From some discussions, it seems like users did not know about the user folder, so some hint is good
This could be a tooltip too

2020-10-02 20:35 UTC, pmiossec commented
> I'm not sure if the "Open app folder" button is really needed though - it feels like it is complicating the UI for a little gain. 🤔

In fact, in the 'App folder', you will find the documentation ('Readme.md') and some examples of existing themes so it's surely a good idea to be able to easily open it. 

And the 'user folder', it's where you must put your custom files. 

I also imagine that someone that want to create its own theme will copy one file from the app folder to the user folder. So it is good to be able to open both.

2020-10-04 22:16 UTC, pmiossec commented
WIP (with some layout problems that I struggle to solve):

![image](https://user-images.githubusercontent.com/460196/95028330-c800e280-069f-11eb-98ec-85ed53176e77.png)

2020-10-04 22:45 UTC, RussKie commented
👍

What kind of layout problems?

On Mon, 5 Oct. 2020, 9:16 am Philippe Miossec, <notifications@github.com>
wrote:

> WIP (with some layout problems that I struggle to solve):
>
> [image: image]
> <https://user-images.githubusercontent.com/460196/95028330-c800e280-069f-11eb-98ec-85ed53176e77.png>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/8502#issuecomment-703323840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBTEXXNXIPVVKI5PKIYSS3SJDX5LANCNFSM4SA6Z4NA>
> .
>

2020-10-04 23:05 UTC, pmiossec commented
> 👍 What kind of layout problems?

1. the "themes" group box and the one above have a width too high and so, the right border is "cropped" even if all the contents are in autosize
2. The split button is automatically set at 'autoresize=true' when compiling even if I would like to stay at 'false'.

2020-10-09 00:28 UTC, RussKie commented
I'll try to look over it on a weekend

2020-10-11 05:50 UTC, RussKie requested changes

2020-10-11 05:52 UTC, RussKie reviewed
👍

2020-10-11 21:22 UTC, pmiossec commented on GitUI/Properties/Resources.Designer.cs
> +                return ((System.Drawing.Bitmap)(obj));
done.

2020-10-11 21:39 UTC, RussKie commented
Merge at will

On Mon, 12 Oct. 2020, 8:22 am Philippe Miossec, <notifications@github.com>
wrote:

> *@pmiossec* commented on this pull request.
> ------------------------------
>
> In GitUI/Properties/Resources.Designer.cs
> <https://github.com/gitextensions/gitextensions/pull/8502#discussion_r502967531>
> :
>
> > +        internal static System.Drawing.Bitmap BrowseFileExplorer {
> +            get {
> +                object obj = ResourceManager.GetObject("BrowseFileExplorer", resourceCulture);
> +                return ((System.Drawing.Bitmap)(obj));
>
> done.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/8502#discussion_r502967531>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBTEXWQCDLX57PVAKDDHPTSKIOZ3ANCNFSM4SA6Z4NA>
> .
>

2020-10-11 23:29 UTC, merged