Fixed "Show in folder" for paths with spaces
gitextensions/gitextensions pull request #8512
Opened 2020-10-03 14:09 UTC by m417z

A simple fix. I didn't test the code, but I tested the command line and it works.

2020-10-03 14:33 UTC, RussKie commented on GitUI/OsShellUtil.cs
> +            Process.Start("explorer.exe", "/select, \"" + filePath + "\"");
We have an extension method
```suggestion
            Process.Start("explorer.exe", $"/select, {filePath.Quote()}");
```

2020-10-03 14:33 UTC, RussKie commented
Please provide your sign off in the contributors.txt

2020-10-03 15:13 UTC, gerhardol requested changes

2020-10-03 15:13 UTC, gerhardol commented on contributors.txt
> +2020/10/03, m417z, ,
Name and email is required (nor use special or ask someone else to use the patch)

2021-01-03 08:14 UTC, RussKie commented
I've tested the current release, and I don't believe there is a problem selecting a file:

![image](https://user-images.githubusercontent.com/4403806/103474422-cf976b00-4df7-11eb-8bff-ee21874e3987.png)
![image](https://user-images.githubusercontent.com/4403806/103474413-b68eba00-4df7-11eb-88af-3304dabf22de.png)

2021-02-05 17:32 UTC, m417z commented
@RussKie you're right, the bug doesn't happen with a space. It does happen when a path contains a comma, though.
For example, this doesn't work: `explorer.exe /select, C:\test,test`
This works (assuming the folder exists): `explorer.exe /select, "C:\test,test"`

2021-04-29 07:59 UTC, closed without merging