Left panel enhancement
gitextensions/gitextensions pull request #8667
Opened 2020-12-09 00:02 UTC by ivangrek

ref #8557

## Proposed changes

- Add textbox with able to change border
- Add toolbar to the left panel

## Screenshots 

### Before

![image](https://user-images.githubusercontent.com/3169265/101555251-ed241100-39c0-11eb-9d28-a71aa861fe7a.png)

![image](https://user-images.githubusercontent.com/3169265/101555262-f319f200-39c0-11eb-933d-1515de34a801.png)

### After

![image](https://user-images.githubusercontent.com/3169265/101555344-28bedb00-39c1-11eb-8f80-182556b45129.png)

![image](https://user-images.githubusercontent.com/3169265/101555426-5015a800-39c1-11eb-9d42-d372618e311c.png)

### Without "Search" label (discussion)

Maybe replace the button too.

![image](https://user-images.githubusercontent.com/3169265/101555660-b8fd2000-39c1-11eb-83f2-8b7ae3a05ab9.png)

![image](https://user-images.githubusercontent.com/3169265/101555584-93701680-39c1-11eb-927c-19b6373d8ec6.png)

## Test methodology 

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

## Test environment(s) 

- GIT 
- Windows 

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2020-12-10 00:48 UTC, RussKie commented
Relates to https://github.com/gitextensions/gitextensions/issues/4814.

A big question - would we plan to add any more functionality to the new panel? For just two buttons it looks kind of like a wasted space.

2020-12-10 01:01 UTC, RussKie requested changes

2020-12-10 01:01 UTC, RussKie commented on GitUI/Win32/MessageCode.cs
> +    public enum MessageCode : int
Win32 messages live here: https://github.com/gitextensions/gitextensions/blob/master/GitUI/Interops/Messages.cs

2020-12-10 01:01 UTC, RussKie commented on GitUI/Win32/NativeMethod.cs
> +    internal static class NativeMethod
Move to https://github.com/gitextensions/gitextensions/tree/master/GitUI/Interops

2020-12-10 01:02 UTC, ivangrek commented
> A big question - would we plan to add any more functionality to the new panel? For just two buttons it looks kind of like a wasted space.

A place for a flight of fantasy. 😄 
You might also wonder why they are not in the context menu.

2020-12-10 01:07 UTC, ivangrek commented on GitUI/UserControls/ExTextBox.cs
> +        }
Ok, I'm trying to separate blocks of code and variable assignments by one line.

2020-12-10 01:08 UTC, RussKie commented
> A place for a flight of fantasy. 😄
> You might also wonder why they are not in the context menu.

Haha, yes. But on a serious note, what would be a good idea to add to this menu? @gitextensions/git-extensions-team 

As for the contextmenu - this requires extra actions (like a right click), and some actions like "expand/collapse all" are not _really_ relevant on individual items, and are better placed at common locations such as this toolpanel.

2020-12-10 01:10 UTC, ivangrek commented on GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
> +            this.showSubmodulesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
Are these prefixes so important? Microsoft does not recommend using them.
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions?redirectedfrom=MSDN

2020-12-10 21:29 UTC, mast-eu commented
> what would be a good idea to add to this menu?

A useful feature would be the ability to change the sorting order, especially for Tags.
When you have tagged many versions following semantic versioning, it can easily happen that you have to scroll down to see the latest versions' tags. I need, however, much more often quick access to the latest versions, rather than the first ones. Inverting the sorting would show the most recent version on top.

2020-12-10 23:28 UTC, vbjay commented
I like martin's idea. To add to it. It would be nice if possible to sort by
how far down the tag is( tag nearest head first, next nearest....).  If
this is not possible then by date of commit. Although date isn't reliable
with rebases involved.

On Thu, Dec 10, 2020, 4:29 PM Martin Steinisch <notifications@github.com>
wrote:

> what would be a good idea to add to this menu?
>
> A useful feature would be the ability to change the sorting order,
> especially for Tags.
> When you have tagged many versions following semantic versioning, it can
> easily happen that you have to scroll down to see the latest versions'
> tags. I need, however, much more often quick access to the latest versions,
> rather than the first ones. Inverting the sorting would show the most
> recent version on top.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/8667#issuecomment-742811431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3WDMMSUPWZE6KHSULS35DSUE4TTANCNFSM4USWPNVQ>
> .
>

2020-12-11 03:58 UTC, RussKie commented
E.g. expose this functionality in the toolbar?
![image](https://user-images.githubusercontent.com/4403806/101860183-583c3600-3bc1-11eb-8ae7-d5c6b929d0c5.png)

2020-12-11 04:03 UTC, RussKie commented on GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
> +            this.showSubmodulesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
Yes. Firstly for consistency purposes. Secondly, when a form/control has a lot of child controls having controls grouped by prefix makes it significantly easier to locate the necessary control. And reason about control type when looking through the list.

2020-12-11 04:50 UTC, RussKie commented on GitUI/UserControls/ExTextBox.cs
> +        }
I don't think in this context "grouping" matters, but creates a lot of dead space, making harder to grasp the code.

2020-12-11 06:25 UTC, ivangrek commented
These buttons.

![image](https://user-images.githubusercontent.com/3169265/101870508-691d8500-3b8a-11eb-90ac-8eb607cede61.png)

2020-12-11 06:27 UTC, RussKie commented
Great, looks like we can fill the toolbar ;)
Let's fix nits, and get this merged.

On Fri, 11 Dec. 2020, 5:25 pm Ivan Grek, <notifications@github.com> wrote:

> These buttons.
>
> [image: image]
> <https://user-images.githubusercontent.com/3169265/101870508-691d8500-3b8a-11eb-90ac-8eb607cede61.png>
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/gitextensions/gitextensions/pull/8667#issuecomment-743000461>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBTEXSBELCTL6BNU72JIUTSUG3PLANCNFSM4USWPNVQ>
> .
>

2020-12-11 07:20 UTC, gerhardol commented
I still prefer to not have an extra row. Remove the Search label and a few more buttons can fit...

2020-12-11 07:28 UTC, ivangrek commented
> I still prefer to not have an extra row. Remove the Search label and a few more buttons can fit...

Tried to follow the UX. In the future, this will make it very easy to add new buttons.

![image](https://user-images.githubusercontent.com/3169265/101875051-a554e380-3b92-11eb-8bb2-e0ff9013fd61.png)

We also have our own UX. I think we will come to this someday.

![image](https://user-images.githubusercontent.com/3169265/101875351-2318ef00-3b93-11eb-838b-6f0c9a78e0d6.png)

2020-12-15 15:28 UTC, ivangrek commented
![image](https://user-images.githubusercontent.com/3169265/102235294-dc145c00-3efa-11eb-9101-01d8314e7fc8.png)

![image](https://user-images.githubusercontent.com/3169265/102235311-e171a680-3efa-11eb-9d06-3f9e191bf75c.png)

2020-12-15 15:53 UTC, pmiossec commented
With a placehoder text it would have been perfect. But perhaps we would have to wait after the .net core migration to have it...

2020-12-15 16:56 UTC, gerhardol commented
> With a placehoder text it would have been perfect. But perhaps we would have to wait after the .net core migration to have it...

We have that in many other boxes already, should be possible.
But this is the same as right now for me, the "Search" label do not add any benefit to the user, there is a search button to the right

2020-12-15 17:07 UTC, pmiossec commented
>But this is the same as right now for me, the "Search" label do not add any benefit to the user, there is a search button to the right

It doesn't add great value, I could admit but for me it improve the UX by letting the user know clearly what is the operation that will be done.
When I see an textbox like that I always wonder if it will do a filter or a search.

And I think that in term of UX, it's better to have a reminder when you enter the field instead than having to analyze the icon and  hoped that the icon has been well chosen...

2020-12-16 23:16 UTC, RussKie commented
> 
> ![image](https://user-images.githubusercontent.com/3169265/101555660-b8fd2000-39c1-11eb-83f2-8b7ae3a05ab9.png)
> 
> ![image](https://user-images.githubusercontent.com/3169265/101555584-93701680-39c1-11eb-927c-19b6373d8ec6.png)

I think I like these more. it aligns with VS design. And this layout is more open to hosting more buttons (that we discussed above).
My 2c.

2020-12-16 23:18 UTC, RussKie commented
Sent too early.

This design is also consistent with other forms we have, e.g.:
![image](https://user-images.githubusercontent.com/4403806/102418063-2576bf80-4051-11eb-9d1a-4cb7bc51032a.png)

2020-12-17 07:42 UTC, ivangrek commented
> This design is also consistent with other forms we have, e.g.

Yes. I talked about this. Search field can be replaced for consistency UI.
At this stage, both options suit me.

Also fixed this case.

![image](https://user-images.githubusercontent.com/3169265/102457671-c8c4d600-404b-11eb-9912-3209a1110494.png)

![image](https://user-images.githubusercontent.com/3169265/102457686-d1b5a780-404b-11eb-8f9e-b4b143853ea2.png)

2020-12-20 06:42 UTC, RussKie commented
> > ![image](https://user-images.githubusercontent.com/3169265/101555660-b8fd2000-39c1-11eb-83f2-8b7ae3a05ab9.png)
> > ![image](https://user-images.githubusercontent.com/3169265/101555584-93701680-39c1-11eb-927c-19b6373d8ec6.png)
> 


I propose we keep this implementation

2020-12-20 09:47 UTC, ivangrek commented
🚀

2020-12-20 10:03 UTC, pmiossec commented
> I propose we keep this implementation

 Are you sure you don't want to keep all on one line until some new icons are added? 😁 (because it looks empty and I find it weird in terms of UI... )

2020-12-20 11:45 UTC, gerhardol commented
> Are you sure you don't want to keep all on one line until some new icons are added? 😁 (because it looks empty and I find it weird in terms of UI... )

I agree, wasted space

2020-12-20 12:28 UTC, RussKie commented
> Are you sure you don't want to keep all on one line until some new icons are added? 😁 (because it looks empty and I find it weird in terms of UI... )

Yes, per the discussion above - there are a number of controls that can/should be placed on the toolbar, e.g.
* https://github.com/gitextensions/gitextensions/pull/8667#issuecomment-742811431
* https://github.com/gitextensions/gitextensions/pull/8667#issuecomment-743000461

2020-12-20 12:44 UTC, ivangrek commented
Roll back the last commit?

2020-12-20 13:52 UTC, ivangrek commented
![image](https://user-images.githubusercontent.com/3169265/102715038-39cded00-42db-11eb-8a2c-375f51041221.png)

![image](https://user-images.githubusercontent.com/3169265/102715043-48b49f80-42db-11eb-9ba3-efdbd281e601.png)

2020-12-20 23:02 UTC, RussKie commented on GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs
> +        private void showBranchesToolStripMenuItem_Click(object sender, EventArgs e)
Event handlers names must match controls

2020-12-20 23:08 UTC, RussKie commented
> ![image](https://user-images.githubusercontent.com/3169265/102715038-39cded00-42db-11eb-8a2c-375f51041221.png)
> ![image](https://user-images.githubusercontent.com/3169265/102715043-48b49f80-42db-11eb-9ba3-efdbd281e601.png)

This has move vote as it allows us to expose more functionality in the toolbar and is consistent with the FormCommit. Judging by comments @mast-eu and @vbjay lean this way as well. 

@gerhardol and @pmiossec I appreciate you are not very enthusiastic about this layout because right now it has empty space (so am I). Once we fill the space, how would you feel about it?

I'd be interested in opinions from @mstv and @NikolayXHD.

2020-12-21 00:07 UTC, gerhardol commented
> @gerhardol and @pmiossec I appreciate you are not very enthusiastic about this layout because right now it has empty space (so am I). Once we fill the space, how would you feel about it?

Fine when we fill the space, just right now it looks weird (up to 4 buttons should be fine, after that they need a separate row)
You have the final decision....

2020-12-21 13:59 UTC, RussKie commented
In the interest of reducing the code churn and incentify us to fill in the glaring void let's move with "the toolbar above the search bar" option.

2020-12-22 12:43 UTC, mstv commented
I have no strong opinion. Since more and more functionality is added to the Left Panel, this seems to be a good preparation.

2020-12-22 13:43 UTC, ivangrek commented
https://user-images.githubusercontent.com/3169265/102894773-49c90680-446c-11eb-921c-37f00e2dc847.mp4

2020-12-22 13:44 UTC, ivangrek commented
🚀

2021-01-03 06:10 UTC, RussKie reviewed
👍 

Please make up the history as well.

2021-01-03 06:10 UTC, RussKie commented on GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
> +            this.leftPanelToolStrip.Text = "toolStrip1";
Redundant

2021-01-03 06:10 UTC, RussKie commented on GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
> +            this.tsbCollapseAll.Text = "toolStripButton1";
ditto

2021-01-03 06:10 UTC, RussKie commented on GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
> +            this.tsmiShowSubmodules});
I don't think we need this dropdown button, suggest removing it and placing the 4 buttons it contains directly on the toolbar

2021-01-03 06:10 UTC, RussKie commented on GitUI/Translation/English.xlf
> +      </trans-unit>
None of these should be here

2021-01-03 06:10 UTC, RussKie commented on GitUI/Interops/NativeMethod.cs
> +﻿using System.Runtime.InteropServices;
This must reside in https://github.com/gitextensions/gitextensions/tree/master/GitUI/Interops/User32 and follow the file and class naming schemes

2021-01-03 06:10 UTC, RussKie commented on GitUI/UserControls/ExTextBox.cs
> +    internal sealed class ExTextBox : TextBox
We have an established naming scheme (for better or for worse):
```suggestion
    internal sealed class TextBoxEx : TextBox
```

2021-01-03 11:52 UTC, ivangrek commented
![image](https://user-images.githubusercontent.com/3169265/103477809-d65bb900-4dca-11eb-8172-2f9deb2e3560.png)

![image](https://user-images.githubusercontent.com/3169265/103477810-d9ef4000-4dca-11eb-8bb1-a07cc95b55f7.png)

2021-01-03 13:52 UTC, RussKie approved these changes

2021-01-03 13:52 UTC, merged