Reset Another branch: prevent special characters in path to fail command
gitextensions/gitextensions pull request #8824
Opened 2021-02-05 21:44 UTC by pmiossec

by using a relative path "." instead...

This is possible because the Working directory of the command run
is the repository folder

Fixes #8822

## Test methodology 

- Manual

## Test environment(s) 

- Git Extensions 33.33.33
- Build f0e6f1b5aad2d765050c319931422057eab29f38
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4261.0
- DPI 192dpi (200% scaling)

2021-02-05 21:54 UTC, mstv approved these changes
Have not run it myself

2021-02-05 22:07 UTC, gerhardol reviewed
+1
Not run

2021-02-05 23:50 UTC, RussKie requested changes

2021-02-05 23:50 UTC, RussKie commented on UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
> +        [TestCase( "mybranch", false, ExpectedResult = @"push . ""1111111111111111111111111111111111111111:mybranch""")]
```suggestion
        [TestCase("mybranch", false, ExpectedResult = @"push . ""1111111111111111111111111111111111111111:mybranch""")]
```

2021-02-05 23:50 UTC, RussKie commented on UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
> +        [TestCase("branch3", true, ExpectedResult = @"push . ""1111111111111111111111111111111111111111:branch3"" --force")]
The 2nd case is redundant

2021-02-06 12:00 UTC, pmiossec commented
done.

2021-02-06 12:00 UTC, RussKie approved these changes

2021-02-08 00:49 UTC, RussKie approved these changes

2021-02-08 00:49 UTC, RussKie commented
Thank you

2021-02-08 00:49 UTC, merged