Don't crash if GE can't check IsDarkTheme
gitextensions/gitextensions pull request #8905
Opened 2021-02-28 14:17 UTC by bansan85

Fixes #8904 

## Proposed changes

- Improve reading file theme.css

### Before

#8904 crashes at startup.

### After

Don't crash.

## Test methodology 

Can't write test without refactoring.

``GitUI.Theming.ThemeModule.Repository`` is private and statically initialized.

To test this class, ThemeModule should be refactored like ``GitUI.Theming.ThemeLoader`` to use interface and add a Load method to customize Repository field.

## Test environment(s) 

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2021-02-28 15:13 UTC, mstv commented on GitUI/Theming/ThemeModule.cs
> +            if (theme.SysColorValues.ContainsKey(KnownColor.Window))
Use `TryGetValue`, please.

2021-02-28 15:13 UTC, mstv commented on GitUI/Theming/ThemeModule.cs
> +            }
Missing newline after `}` let's the build fail.
```suggestion
            }
            
```

2021-02-28 16:01 UTC, mstv approved these changes
Thank you.

2021-02-28 22:51 UTC, gerhardol requested changes
According to 
https://github.com/gitextensions/gitextensions/issues/8904#issuecomment-787517984

2021-02-28 22:58 UTC, gerhardol approved these changes

2021-03-01 00:39 UTC, RussKie commented
@NikolayXHD is this fix still required with #8907?

2021-03-01 09:36 UTC, bansan85 commented
@RussKie No. #8907 already have the fix.

2021-03-01 09:36 UTC, closed without merging