Replace deprecated SmtpClient with Mailkit
gitextensions/gitextensions pull request #9137
Opened 2021-05-02 12:14 UTC by EbenZhang

Fixes #3856

## Proposed changes

- Smtpclient was deprecated https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-5.0
- Microsoft suggests use Mailkit instead

## Test methodology 

- Use the format patch dialog and successfully send the patch to my email

## Test environment(s) 

- GIT: git version 2.29.1.windows.1
- Windows 10

----

:black_nib: I contribute this code under [The Developer Certificate of Origin](../blob/master/contributors.txt).

2021-05-03 19:32 UTC, mstv reviewed
Thank you. It works for me.
Voting +1 but not approving because I am not sure about the code style.

2021-05-04 03:18 UTC, RussKie requested changes
The installer and the portable bundle must be updated as well to include the new dependency.

2021-05-04 03:18 UTC, RussKie commented on GitUI/CommandsDialogs/FormFormatPatch.cs
> +                    var attachment = new MimePart()
```suggestion
                    var attachment = new MimePart
```

2021-05-05 05:02 UTC, EbenZhang commented
@RussKie, the Mailkit.dll is in the portal automatically: https://ci.appveyor.com/api/buildjobs/3ewt6aopfax8xxvg/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-3.6.0.11771-43a5e53eb.zip

2021-05-05 05:08 UTC, EbenZhang commented on GitUI/CommandsDialogs/FormFormatPatch.cs
> +                    var attachment = new MimePart()
removed

2021-05-26 03:42 UTC, RussKie commented
MC.

New dependencies affect the installer, and it must be updated accordingly.

2021-08-02 08:51 UTC, EbenZhang commented
![image](https://user-images.githubusercontent.com/596334/127832946-15aa12e4-56b2-4c82-ab99-9a9d2defde51.png)
which kind of feedback do you need?

2021-08-02 08:54 UTC, EbenZhang commented
> MC.
> 
> New dependencies affect the installer, and it must be updated accordingly.

Need to add the dll to the installer/MSI?

2021-12-07 12:32 UTC, NN--- commented on GitUI/CommandsDialogs/FormFormatPatch.cs
> +                attachmentStreams.ForEach(x => x.Dispose());
Do not introduce premature code pessimisation.
This works faster and has the same amount of characters.

```suggestion
                foreach (var x in attachmentStreams) x.Dispose();
```

2022-09-03 07:29 UTC, closed without merging

2022-09-03 07:29 UTC, RussKie commented
Closing as stale