Move the init logic from OnLoad to InternalInitialize
gitextensions/gitextensions pull request #9591
Opened 2021-09-26 07:51 UTC by RussKie

Addendum to #9106

Fixes #

## Proposed changes

If the app is opened with `browse <repo>` we would execute a number of instructions that we wouldn't execute if the app was opened in the dashboard-mode. Those instructions included initialising the "Push" button, the revision grid, and loading the splitters state.

Move these instructions into `InternalInitialize` method, that gets executed whenever a dashboard is shown or a repo is loaded. This way we unify the flow, and contain repo-init instructions in one place.

## Test methodology 

- manual

2021-09-26 21:54 UTC, gerhardol requested changes
regression...
Should we include changes like this in 3.5?
They take some extra time to review and test (changes to master are easier to use).

2021-09-26 21:54 UTC, gerhardol commented on GitUI/CommandsDialogs/FormBrowse.cs
> -            UpdateStashCount();
Submodules and stash count are no longer updated when opening a repo directly

2021-09-29 08:01 UTC, RussKie commented
> Should we include changes like this in 3.5?

No :) I've been sitting on the fence, but I have limited the surface of the change to the splitters only.

2021-09-29 08:18 UTC, merged

2022-10-18 02:45 UTC, Juscc53 reviewed
[SPAM]

2022-10-18 04:31 UTC, vbjay commented
![Screenshot_20221018-003032_Gmail.jpg](https://user-images.githubusercontent.com/3629489/196335946-9717fd5a-31c8-4c78-8a14-e0c5127a943d.jpg)
Reported.